In [1]:
import numpy as np

In [2]:
col_vec = np.array([[11],[22],[33]])

In [3]:
col_vec

array([[11],
       [22],
       [33]])

In [4]:
row_vec = col_vec.T

In [5]:
row_vec

array([[11, 22, 33]])

In [6]:
col_times_row = col_vec * row_vec

In [7]:
col_times_row

array([[ 121,  242,  363],
       [ 242,  484,  726],
       [ 363,  726, 1089]])

In [8]:
col_vec.shape

(3, 1)

In [9]:
row_vec.shape

(1, 3)

In [10]:
col_times_row.shape

(3, 3)

In [11]:
row_times_col = row_vec * col_vec

In [12]:
row_times_col

array([[ 121,  242,  363],
       [ 242,  484,  726],
       [ 363,  726, 1089]])

In [13]:
row_times_row = row_vec * row_vec

In [14]:
row_times_row

array([[ 121,  484, 1089]])

In [16]:
#row_dot_row = np.dot(row_vec,row_vec)

In [17]:
row_dot_col = np.dot(row_vec,col_vec)

In [18]:
row_dot_col

array([[1694]])

In [19]:
row_dot_col.shape

(1, 1)

In [20]:
col_dot_row = np.dot(col_vec,row_vec)

In [21]:
col_dot_row

array([[ 121,  242,  363],
       [ 242,  484,  726],
       [ 363,  726, 1089]])