In [1]:
import matplotlib.pyplot as plt
import numpy as np

import time

import sys
import os

from datetime import datetime
import subprocess

from os.path import exists

import read_config_utils as cu

from pathlib import Path


In [2]:
base_dir = 'output-files-bootstrap-test6b-6d-1b'

In [3]:
input_dir = '%s/fit-results' % base_dir

In [4]:
pathlist = Path(input_dir).glob('**/fit-boot*.npy')

In [5]:
pathlist

<generator object Path.glob at 0x7fded4ec9850>

In [6]:
n_fits = 0
ndim = 0
pathlist = Path(input_dir).glob('**/fit-boot*.npy')
for path in pathlist :
    if n_fits == 0 :
        input_file = str(path)
        print( '%s' % input_file )
        with open( input_file, 'rb' ) as f :
            fit_results_mean_val = np.load(f)      
        ndim = fit_results_mean_val.shape[0]
        print('shape %s' % str(fit_results_mean_val.shape))
    # print( '%s' % str(path))
    n_fits = n_fits + 1
    
        
print("\n found %d bootstrap fits.  ndim = %d\n" % (n_fits, ndim) )

output-files-bootstrap-test6b-6d-1b/fit-results/fit-bootstrap-weights-021.npy
shape (6,)

 found 50 bootstrap fits.  ndim = 6



In [7]:
all_fit_results_mean_val = np.zeros( shape=(ndim, n_fits ) )
all_fit_results_mean_err = np.zeros( shape=(ndim, n_fits ) )
all_fit_results_cov_val = np.zeros( shape=(ndim, ndim, n_fits ) )
all_fit_results_cov_err = np.zeros( shape=(ndim, ndim, n_fits ) )

In [8]:
#pathlist = Path(input_dir).glob('**/fit-boot*.npy')
#fi = 0
#for path in pathlist :
#    input_file = str(path)
#    print( '%s' % input_file )
#    with open( input_file, 'rb' ) as f :
#        fit_results_mean_val = np.load(f)
#        fit_results_mean_err = np.load(f)
#        fit_results_cov_val = np.load(f)
#        fit_results_cov_err = np.load(f)
#    print(fit_results_mean_val)
#    all_fit_results_mean_val[:,fi] = fit_results_mean_val
#    all_fit_results_mean_err[:,fi] = fit_results_mean_err
#    all_fit_results_cov_val[:,:,fi] = fit_results_cov_val
#    all_fit_results_cov_err[:,:,fi] = fit_results_cov_err
#    fi = fi + 1

In [9]:
for fi in range(n_fits) :
    input_file = '%s/fit-bootstrap-weights-%03d.npy' % (input_dir, fi)
    print( '%s' % input_file )
    with open( input_file, 'rb' ) as f :
        fit_results_mean_val = np.load(f)
        fit_results_mean_err = np.load(f)
        fit_results_cov_val = np.load(f)
        fit_results_cov_err = np.load(f)
    print(fit_results_mean_val)
    all_fit_results_mean_val[:,fi] = fit_results_mean_val
    all_fit_results_mean_err[:,fi] = fit_results_mean_err
    all_fit_results_cov_val[:,:,fi] = fit_results_cov_val
    all_fit_results_cov_err[:,:,fi] = fit_results_cov_err    

output-files-bootstrap-test6b-6d-1b/fit-results/fit-bootstrap-weights-000.npy
[ 0.79936163  0.10583456 -0.61603067  0.70303986 -0.81004125  0.10848583]
output-files-bootstrap-test6b-6d-1b/fit-results/fit-bootstrap-weights-001.npy
[ 0.80128749  0.10330201 -0.61577636  0.70234626 -0.80316528  0.10840544]
output-files-bootstrap-test6b-6d-1b/fit-results/fit-bootstrap-weights-002.npy
[ 0.79782154  0.10540727 -0.62058367  0.70390759 -0.80791332  0.11015246]
output-files-bootstrap-test6b-6d-1b/fit-results/fit-bootstrap-weights-003.npy
[ 0.80329252  0.10955095 -0.61736856  0.70645687 -0.8072772   0.11032573]
output-files-bootstrap-test6b-6d-1b/fit-results/fit-bootstrap-weights-004.npy
[ 0.79934422  0.10803796 -0.62533946  0.70641455 -0.8084596   0.10688477]
output-files-bootstrap-test6b-6d-1b/fit-results/fit-bootstrap-weights-005.npy
[ 0.8006055   0.10688055 -0.62447599  0.70788204 -0.80551192  0.10827281]
output-files-bootstrap-test6b-6d-1b/fit-results/fit-bootstrap-weights-006.npy
[ 0.805542

In [10]:
all_fit_results_mean_val

array([[ 0.79936163,  0.80128749,  0.79782154,  0.80329252,  0.79934422,
         0.8006055 ,  0.80554209,  0.80624077,  0.80502337,  0.79997762,
         0.80078904,  0.80081752,  0.80069922,  0.80251335,  0.80485749,
         0.8014607 ,  0.79993325,  0.80074553,  0.80020212,  0.80252134,
         0.80375376,  0.80002561,  0.80027573,  0.80256135,  0.80324764,
         0.79889442,  0.79683328,  0.80392705,  0.80334827,  0.79730148,
         0.80153155,  0.79988381,  0.79966559,  0.79874636,  0.80023468,
         0.80255422,  0.79954513,  0.79720251,  0.80066092,  0.79983867,
         0.8053063 ,  0.80115344,  0.80187357,  0.80079292,  0.80348077,
         0.8010173 ,  0.79290192,  0.80226775,  0.80578805,  0.80005601],
       [ 0.10583456,  0.10330201,  0.10540727,  0.10955095,  0.10803796,
         0.10688055,  0.10666994,  0.10598935,  0.10206803,  0.11275429,
         0.11001757,  0.11062622,  0.10982446,  0.11418813,  0.10859841,
         0.10699541,  0.10506135,  0.10732348,  0.

In [11]:
all_fit_results_cov_val

array([[[ 6.55051259e-01,  6.60730462e-01,  6.58153546e-01, ...,
          6.53714357e-01,  6.51991415e-01,  6.56904454e-01],
        [ 1.14607385e-02,  1.23542983e-02,  1.46380136e-02, ...,
          1.55586319e-02,  1.53929289e-02,  1.58902577e-02],
        [ 1.33593631e-01,  1.32092144e-01,  1.31867747e-01, ...,
          1.32566532e-01,  1.32695369e-01,  1.36863448e-01],
        [-9.14105019e-02, -9.20866243e-02, -8.85044947e-02, ...,
         -8.70012550e-02, -8.93142690e-02, -9.22324076e-02],
        [ 6.44873226e-02,  6.79444332e-02,  6.74582245e-02, ...,
          6.23965235e-02,  6.38012026e-02,  6.15370211e-02],
        [ 1.12293620e-02,  1.81884518e-02,  1.02304189e-02, ...,
          1.02515291e-02,  1.24533725e-02,  1.51670782e-02]],

       [[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 3.90461740e-01,  3.89812925e-01,  3.91928439e-01, ...,
          4.00342294e-01,  4.02123793e-01,  4.05380

In [12]:
with open( '%s/fit-results.npy' % base_dir, 'wb' ) as f :
    np.save( f, all_fit_results_mean_val )
    np.save( f, all_fit_results_mean_err )
    np.save( f, all_fit_results_cov_val )
    np.save( f, all_fit_results_cov_err )