In [1]:
import matplotlib.pyplot as plt
import numpy as np

import time

import sys
import os

from datetime import datetime
import subprocess

from os.path import exists

import read_config_utils as cu

from pathlib import Path


In [2]:
base_dir = 'output-files-bootstrap-test6b-6d'

In [3]:
input_dir = '%s/fit-results' % base_dir

In [4]:
pathlist = Path(input_dir).glob('**/fit-boot*.npy')

In [5]:
pathlist

<generator object Path.glob at 0x7f9bfc6a1850>

In [6]:
n_fits = 0
ndim = 0
pathlist = Path(input_dir).glob('**/fit-boot*.npy')
for path in pathlist :
    if n_fits == 0 :
        input_file = str(path)
        print( '%s' % input_file )
        with open( input_file, 'rb' ) as f :
            fit_results_mean_val = np.load(f)      
        ndim = fit_results_mean_val.shape[0]
        print('shape %s' % str(fit_results_mean_val.shape))
    # print( '%s' % str(path))
    n_fits = n_fits + 1
    
        
print("\n found %d bootstrap fits.  ndim = %d\n" % (n_fits, ndim) )

output-files-bootstrap-test6b-6d/fit-results/fit-bootstrap-weights-021.npy
shape (6,)

 found 50 bootstrap fits.  ndim = 6



In [7]:
all_fit_results_mean_val = np.zeros( shape=(ndim, n_fits ) )
all_fit_results_mean_err = np.zeros( shape=(ndim, n_fits ) )
all_fit_results_cov_val = np.zeros( shape=(ndim, ndim, n_fits ) )
all_fit_results_cov_err = np.zeros( shape=(ndim, ndim, n_fits ) )

In [8]:
#pathlist = Path(input_dir).glob('**/fit-boot*.npy')
#fi = 0
#for path in pathlist :
#    input_file = str(path)
#    print( '%s' % input_file )
#    with open( input_file, 'rb' ) as f :
#        fit_results_mean_val = np.load(f)
#        fit_results_mean_err = np.load(f)
#        fit_results_cov_val = np.load(f)
#        fit_results_cov_err = np.load(f)
#    print(fit_results_mean_val)
#    all_fit_results_mean_val[:,fi] = fit_results_mean_val
#    all_fit_results_mean_err[:,fi] = fit_results_mean_err
#    all_fit_results_cov_val[:,:,fi] = fit_results_cov_val
#    all_fit_results_cov_err[:,:,fi] = fit_results_cov_err
#    fi = fi + 1

In [9]:
for fi in range(n_fits) :
    input_file = '%s/fit-bootstrap-weights-%03d.npy' % (input_dir, fi)
    print( '%s' % input_file )
    with open( input_file, 'rb' ) as f :
        fit_results_mean_val = np.load(f)
        fit_results_mean_err = np.load(f)
        fit_results_cov_val = np.load(f)
        fit_results_cov_err = np.load(f)
    print(fit_results_mean_val)
    all_fit_results_mean_val[:,fi] = fit_results_mean_val
    all_fit_results_mean_err[:,fi] = fit_results_mean_err
    all_fit_results_cov_val[:,:,fi] = fit_results_cov_val
    all_fit_results_cov_err[:,:,fi] = fit_results_cov_err    

output-files-bootstrap-test6b-6d/fit-results/fit-bootstrap-weights-000.npy
[ 0.80079333  0.10038667 -0.60384716  0.6987156  -0.80255407  0.09366647]
output-files-bootstrap-test6b-6d/fit-results/fit-bootstrap-weights-001.npy
[ 0.79853218  0.10162968 -0.60288977  0.70025171 -0.80479689  0.09001479]
output-files-bootstrap-test6b-6d/fit-results/fit-bootstrap-weights-002.npy
[ 0.80030448  0.10196455 -0.60148769  0.70056557 -0.80164687  0.09618187]
output-files-bootstrap-test6b-6d/fit-results/fit-bootstrap-weights-003.npy
[ 0.79921402  0.09939437 -0.60519945  0.70146158 -0.79816567  0.09691784]
output-files-bootstrap-test6b-6d/fit-results/fit-bootstrap-weights-004.npy
[ 0.80026079  0.10089673 -0.60417221  0.70228575 -0.79639194  0.09482374]
output-files-bootstrap-test6b-6d/fit-results/fit-bootstrap-weights-005.npy
[ 0.79975017  0.10249963 -0.6028425   0.69982053 -0.79724926  0.10050611]
output-files-bootstrap-test6b-6d/fit-results/fit-bootstrap-weights-006.npy
[ 0.79896494  0.10118139 -0.598

In [10]:
all_fit_results_mean_val

array([[ 0.80079333,  0.79853218,  0.80030448,  0.79921402,  0.80026079,
         0.79975017,  0.79896494,  0.80134277,  0.79755627,  0.79958114,
         0.79980208,  0.80094219,  0.80213641,  0.79491759,  0.79826739,
         0.79865763,  0.79499466,  0.80174484,  0.79933919,  0.79607783,
         0.79728739,  0.79843063,  0.79939924,  0.80029145,  0.79532806,
         0.80087195,  0.79699456,  0.79967861,  0.79910853,  0.79773234,
         0.79759728,  0.80009163,  0.79859443,  0.79701463,  0.79570256,
         0.79930764,  0.79843817,  0.79832616,  0.79496659,  0.79570958,
         0.79693594,  0.79914488,  0.7996892 ,  0.79787538,  0.79779143,
         0.79904384,  0.79925441,  0.79828708,  0.79947274,  0.80011325],
       [ 0.10038667,  0.10162968,  0.10196455,  0.09939437,  0.10089673,
         0.10249963,  0.10118139,  0.10170632,  0.10054458,  0.10068483,
         0.10259046,  0.10255045,  0.10036785,  0.10331753,  0.09998873,
         0.10156307,  0.10032248,  0.10227152,  0.

In [11]:
all_fit_results_cov_val

array([[[ 6.38208933e-01,  6.38549847e-01,  6.40118180e-01, ...,
          6.39364729e-01,  6.39863649e-01,  6.38855719e-01],
        [ 2.12270392e-03,  1.12969319e-04, -9.46042103e-04, ...,
          2.65340866e-03, -2.75016899e-03,  3.60795949e-04],
        [ 1.54006214e-01,  1.52109636e-01,  1.53584284e-01, ...,
          1.54128952e-01,  1.53337223e-01,  1.58019817e-01],
        [-9.58797212e-02, -9.30840125e-02, -9.71072546e-02, ...,
         -9.47361826e-02, -9.73259158e-02, -9.54573540e-02],
        [ 7.87973669e-02,  7.89956847e-02,  7.87822330e-02, ...,
          8.20264656e-02,  7.97076369e-02,  7.76017112e-02],
        [ 1.79978427e-03,  5.49206761e-04,  2.46462695e-03, ...,
          4.28304638e-03,  7.58385522e-04,  6.53695757e-04]],

       [[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 3.60244574e-01,  3.59368131e-01,  3.59605551e-01, ...,
          3.58737938e-01,  3.58931248e-01,  3.61941

In [12]:
with open( '%s/fit-results.npy' % base_dir, 'wb' ) as f :
    np.save( f, all_fit_results_mean_val )
    np.save( f, all_fit_results_mean_err )
    np.save( f, all_fit_results_cov_val )
    np.save( f, all_fit_results_cov_err )