In [1]:
import matplotlib.pyplot as plt
import numpy as np

import time

import sys
import os

from datetime import datetime
import subprocess

from os.path import exists

os.environ['CUDA_VISIBLE_DEVICES']="1"


from keras.layers import Dense, Input
from keras.models import Model

import omnifold6 as of

import tensorflow as tf

import gc

import read_config_utils as cu


In [2]:
print("\n\n")
print("  numpy version:  %s" % str(np.version.version) )
print("  tensorflow version:  %s" % str(tf.__version__))
print("\n\n")




  numpy version:  1.21.5
  tensorflow version:  2.11.0





In [3]:
output_dir = 'output-files-bootstrap-test6b-2d-2a'


do_bootstrap = True


config_file = '%s/config.txt' % output_dir

if not exists( config_file ) :
    
    print('\n\n can not find config file:  %s' % config_file )
    print('\n\n HALTING EXECUTION\n\n')
    sys.exit()

    
print('\n\n  Config file contents : %s\n' % config_file )
print( subprocess.getoutput('cat %s' % config_file ))
print('\n\n')

ndim = int(cu.get_par( config_file, "ndim"))
print(" Number of feature dimensions: %d" % ndim)

n_boot_samples = int( cu.get_par( config_file, "n_boot_samples") )
print(" Number of bootstrap samples: %d" % n_boot_samples )

of_niter = int( cu.get_par( config_file, "of_niter") )
print(" Number of OmniFold iterations: %d" % of_niter )

batch_size_setval = int( cu.get_par( config_file, "batch_size_setval") )
print(" Batch size setval: %d" % batch_size_setval )

epochs_setval = int( cu.get_par( config_file, "epochs_setval") )
print(" Epochs size setval: %d" % epochs_setval )

learning_rate_setval = float( cu.get_par( config_file, "learning_rate_setval") )
print(" Learning rate setval: %f" % learning_rate_setval )

print("\n\n\n")





  Config file contents : output-files-bootstrap-test6b-2d-2a/config.txt

2023-12-15 19:11:54.367588

ngen_train 400000
ngen_true  40000
of_niter   10
ndim       2
learning_rate_setval  0.000500
epochs_setval  40
batch_size_setval  40000
n_boot_samples  500
do_bootstrap  1


train_mu : [0.0, 1.0]
train_rho : [[-0.6]]
train_sig : [1.0, 1.5]


true_mu : [0.2, 0.8]
true_rho : [[-0.6]]
true_sig : [0.9, 1.3]


resolution : [0.5, 0.8]



 Number of feature dimensions: 2
 Number of bootstrap samples: 500
 Number of OmniFold iterations: 10
 Batch size setval: 40000
 Epochs size setval: 40
 Learning rate setval: 0.000500






In [4]:
last_bs_file_index = 0

for bsi in range(1000) :
    
    fname = '%s/bootstrap-weights-%03d.npy' % (output_dir, bsi)
    
    if exists(fname) and bsi > last_bs_file_index :
        
        last_bs_file_index = bsi
        
print("\n\n Last bootstrap index found is %d\n\n" % last_bs_file_index )





 Last bootstrap index found is 365




## Read in the samples from file

In [5]:
with open( '%s/train-and-true-samples.npy' % output_dir, 'rb') as f :
    train_pts = np.load(f)
    train_det_pts = np.load(f)
    true_pts = np.load(f)
    true_det_pts = np.load(f)
    
print('\n\n')
print(' shape of train_pts:  %s' % str(train_pts.shape))
print(' shape of true_pts:   %s' % str(true_pts.shape))
print('\n\n')




 shape of train_pts:  (400000, 2)
 shape of true_pts:   (40000, 2)





## Set up NN model for OmniFold

In [6]:
inputs = Input((ndim, ))
hidden_layer_1 = Dense(50, activation='relu')(inputs)
hidden_layer_2 = Dense(50, activation='relu')(hidden_layer_1)
hidden_layer_3 = Dense(50, activation='relu')(hidden_layer_2)
outputs = Dense(1, activation='sigmoid')(hidden_layer_3)
model = Model(inputs=inputs, outputs=outputs)

2023-12-16 08:52:23.327803: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-12-16 08:52:23.356802: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-12-16 08:52:23.357104: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-12-16 08:52:23.362027: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-12-16 08:52:23.362289: I tensorflow/compiler/xla/stream_executo

## Package the training data for OmniFold

In [7]:
train_both = np.stack([train_pts, train_det_pts], axis=1)

## Do the bootstrap samples in a loop

In [8]:

verbose = False



In [9]:
%%time

rng = np.random.default_rng()

for bi in range(last_bs_file_index+1,n_boot_samples) :
    
    if do_bootstrap :
        print("\n Creating bootstrap sample %3d" % bi )
        boot_true_det_pts = rng.choice( true_det_pts, size=len(true_det_pts) )
        
    else :
        print("\n Creating toy sample %3d" % bi )
        boot_true_pts = np.random.multivariate_normal(true_mu, true_cov, size=ngen_true)
        boot_true_det_pts = np.random.normal( boot_true_pts, [res0, res1])
        

        
    boot_of_return_dict = of.omnifold6( 
        train_both, boot_true_det_pts, of_niter, model, verbose, 
        batch_size_setval, learning_rate_setval, epochs_setval )



    mc_weight_sf = (1.*len(boot_true_det_pts))/(1.*len(train_both))



    boot_final_push_weights = boot_of_return_dict["final_push_weights"]
    #boot_final_push_weights_scaled = np.copy(boot_final_push_weights)
    boot_final_push_weights_scaled = boot_final_push_weights
    boot_final_push_weights_scaled = mc_weight_sf * boot_final_push_weights
    
    print("\n\n bootstrap %d final push weights scaled:" % bi)
    print( boot_final_push_weights_scaled )

    

     
    with open( '%s/bootstrap-weights-%03d.npy' % ( output_dir, bi ), 'wb' ) as f :
        np.save( f, boot_final_push_weights_scaled )
        
    del boot_of_return_dict
    gc.collect()
    


 Creating bootstrap sample 366
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]


2023-12-16 08:52:25.719909: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:630] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
2023-12-16 08:52:25.722013: I tensorflow/compiler/xla/service/service.cc:173] XLA service 0x7fd3b52bf130 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-12-16 08:52:25.722026: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (0): NVIDIA GeForce RTX 3090, Compute Capability 8.6
2023-12-16 08:52:25.725911: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2023-12-16 08:52:25.818843: I tensorflow/compiler/jit/xla_compilation_cache.cc:477] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


40/40 [==============================] - 0s 611us/step
 weights_push at the beginning
[0.89113641 0.46798375 0.30148435 ... 1.02306879 1.22187889 0.76387012]
40/40 [==============================] - 0s 608us/step
 weights_push at the beginning
[0.85443584 0.38763002 0.22419656 ... 0.95581518 1.29634168 0.7211418 ]
40/40 [==============================] - 0s 592us/step
 weights_push at the beginning
[0.85113629 0.35925093 0.19072078 ... 0.89848051 1.31274876 0.710878  ]
40/40 [==============================] - 0s 599us/step
 weights_push at the beginning
[0.83771188 0.33503223 0.16229644 ... 0.87009678 1.33950714 0.71889201]
40/40 [==============================] - 0s 656us/step
 weights_push at the beginning
[0.84962454 0.32565869 0.15139168 ... 0.84663766 1.35830008 0.73061737]
40/40 [==============================] - 0s 658us/step
 weights_push at the beginning
[0.85377573 0.33388995 0.15623106 ... 0.82944609 1.38389865 0.75253509]
40/40 [==============================] - 0s 538us/st

40/40 [==============================] - 0s 581us/step
 weights_push at the beginning
[0.81142877 0.32495768 0.13586743 ... 0.78875143 1.17911561 0.64326148]
40/40 [==============================] - 0s 644us/step
 weights_push at the beginning
[0.81205761 0.31387757 0.12597667 ... 0.77918969 1.1695218  0.63322474]
40/40 [==============================] - 0s 647us/step


 bootstrap 369 final push weights scaled:
[0.08118559 0.03109975 0.01237623 ... 0.07539491 0.11472484 0.06427537]

 Creating bootstrap sample 370
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]
40/40 [==============================] - 0s 635us/step
 weights_push at the beginning
[0.91011691 0.46589512 0.26020846 ... 0.98291159 1.15851557 0.755301  ]
40/40 [==============================] - 0s 606us/step
 weights_push at the beginning
[0.91088668 0.39626503 0.1876441  ... 0.89995069 1.23398543 0.7422631 ]
40/40 [==============================] - 0s 619us/step
 weights_push at the beginning
[0.90663656 0.38684275 0

40/40 [==============================] - 0s 605us/step
 weights_push at the beginning
[0.9746019  0.52059061 0.27051051 ... 0.65612659 1.46845306 0.68686348]
40/40 [==============================] - 0s 650us/step
 weights_push at the beginning
[1.00855911 0.53985715 0.28867142 ... 0.61693964 1.50196595 0.68302553]
40/40 [==============================] - 0s 616us/step
 weights_push at the beginning
[1.00225265 0.55073981 0.29472564 ... 0.57015796 1.47394588 0.66853102]
40/40 [==============================] - 0s 618us/step
 weights_push at the beginning
[1.03420628 0.5792426  0.32271043 ... 0.53609257 1.46447337 0.6626292 ]
40/40 [==============================] - 0s 629us/step
 weights_push at the beginning
[1.07747323 0.60869123 0.33602212 ... 0.50718565 1.48481355 0.66131328]
40/40 [==============================] - 0s 644us/step


 bootstrap 373 final push weights scaled:
[0.1092951  0.0596125  0.03193105 ... 0.04710498 0.15073624 0.06523532]

 Creating bootstrap sample 374
 weight

40/40 [==============================] - 0s 616us/step
 weights_push at the beginning
[0.91122887 0.40659881 0.25122876 ... 0.82872348 1.24154962 0.74226575]
40/40 [==============================] - 0s 603us/step
 weights_push at the beginning
[0.92103322 0.38376433 0.22528466 ... 0.75473751 1.26111727 0.75530269]
40/40 [==============================] - 0s 576us/step
 weights_push at the beginning
[0.93203486 0.38004774 0.22348327 ... 0.68435047 1.25527127 0.75580925]
40/40 [==============================] - 0s 621us/step
 weights_push at the beginning
[0.93985791 0.39347113 0.23893719 ... 0.66485071 1.25790463 0.76366763]
40/40 [==============================] - 0s 626us/step
 weights_push at the beginning
[0.94834706 0.398682   0.24676991 ... 0.62394796 1.23593466 0.7747401 ]
40/40 [==============================] - 0s 606us/step
 weights_push at the beginning
[0.94796144 0.39291792 0.2453337  ... 0.61404547 1.24315421 0.76141675]
40/40 [==============================] - 0s 665us/st

40/40 [==============================] - 0s 612us/step
 weights_push at the beginning
[1.18571967 0.43237017 0.15955791 ... 0.33923839 1.46287584 0.68863661]
40/40 [==============================] - 0s 613us/step


 bootstrap 380 final push weights scaled:
[0.12275568 0.044633   0.01612682 ... 0.0301712  0.144994   0.06874781]

 Creating bootstrap sample 381
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]
40/40 [==============================] - 0s 609us/step
 weights_push at the beginning
[0.92345482 0.47596824 0.31749251 ... 0.8731584  1.18034041 0.77938831]
40/40 [==============================] - 0s 648us/step
 weights_push at the beginning
[0.94061268 0.40482798 0.2368957  ... 0.79196055 1.28867635 0.74591086]
40/40 [==============================] - 0s 660us/step
 weights_push at the beginning
[0.96943575 0.38409877 0.20922689 ... 0.65441279 1.36028595 0.73523234]
40/40 [==============================] - 0s 666us/step
 weights_push at the beginning
[0.98736763 0.38192885 0

40/40 [==============================] - 0s 564us/step
 weights_push at the beginning
[0.99318306 0.39222301 0.21367982 ... 0.48670142 1.33280237 0.72496699]
40/40 [==============================] - 0s 561us/step
 weights_push at the beginning
[1.020453   0.40570991 0.22613866 ... 0.45572533 1.36425346 0.75149922]
40/40 [==============================] - 0s 589us/step
 weights_push at the beginning
[1.00356164 0.4045483  0.22584502 ... 0.41111236 1.3849246  0.7469845 ]
40/40 [==============================] - 0s 632us/step
 weights_push at the beginning
[1.03696043 0.43310088 0.25407848 ... 0.37288651 1.43118595 0.76233772]
40/40 [==============================] - 0s 630us/step


 bootstrap 384 final push weights scaled:
[0.1068114  0.04365429 0.02579049 ... 0.03342022 0.14520806 0.07599854]

 Creating bootstrap sample 385
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]
40/40 [==============================] - 0s 638us/step
 weights_push at the beginning
[0.92689222 0.48819306 0

40/40 [==============================] - 0s 610us/step
 weights_push at the beginning
[0.80390832 0.35279708 0.18055246 ... 0.7247886  1.37139411 0.76920581]
40/40 [==============================] - 0s 641us/step
 weights_push at the beginning
[0.79266444 0.34542799 0.17039737 ... 0.62707745 1.39526752 0.78724617]
40/40 [==============================] - 0s 630us/step
 weights_push at the beginning
[0.73932396 0.33762661 0.16274806 ... 0.58414564 1.45734577 0.79187405]
40/40 [==============================] - 0s 628us/step
 weights_push at the beginning
[0.68958331 0.32556154 0.15472661 ... 0.50578733 1.45596636 0.8032795 ]
40/40 [==============================] - 0s 550us/step
 weights_push at the beginning
[0.68361734 0.34117164 0.16446883 ... 0.46312459 1.48055181 0.8285735 ]
40/40 [==============================] - 0s 649us/step
 weights_push at the beginning
[0.6657465  0.3399422  0.16128038 ... 0.41819386 1.49620166 0.82125269]
40/40 [==============================] - 0s 627us/st

40/40 [==============================] - 0s 639us/step


 bootstrap 391 final push weights scaled:
[0.09160217 0.04986965 0.03134697 ... 0.02857883 0.15453136 0.08804104]

 Creating bootstrap sample 392
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]
40/40 [==============================] - 0s 629us/step
 weights_push at the beginning
[0.93488085 0.45688871 0.32771316 ... 0.92858434 1.22999144 0.70867592]
40/40 [==============================] - 0s 609us/step
 weights_push at the beginning
[0.96947663 0.4224259  0.28230581 ... 0.89065417 1.38142323 0.68994755]
40/40 [==============================] - 0s 628us/step
 weights_push at the beginning
[0.97497883 0.4336158  0.27788339 ... 0.82984314 1.4857734  0.68885711]
40/40 [==============================] - 0s 626us/step
 weights_push at the beginning
[0.94045624 0.43545337 0.27314546 ... 0.75373706 1.52753268 0.68006131]
40/40 [==============================] - 0s 622us/step
 weights_push at the beginning
[0.9264387  0.47040837 0

40/40 [==============================] - 0s 642us/step
 weights_push at the beginning
[0.86797309 0.45202914 0.24850964 ... 0.55389288 1.37770929 0.66219126]
40/40 [==============================] - 0s 611us/step
 weights_push at the beginning
[0.86227756 0.45454713 0.26508756 ... 0.48859134 1.37258217 0.63565421]
40/40 [==============================] - 0s 639us/step
 weights_push at the beginning
[0.8913179  0.45988648 0.28570064 ... 0.4283941  1.41729585 0.61967255]
40/40 [==============================] - 0s 626us/step


 bootstrap 395 final push weights scaled:
[0.08894699 0.04721785 0.03174663 ... 0.03754897 0.14430611 0.06059658]

 Creating bootstrap sample 396
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]
40/40 [==============================] - 0s 618us/step
 weights_push at the beginning
[0.90032643 0.50241166 0.3093397  ... 0.9583829  1.24132311 0.72697848]
40/40 [==============================] - 0s 669us/step
 weights_push at the beginning
[0.85116319 0.41085773 0

40/40 [==============================] - 0s 619us/step
 weights_push at the beginning
[0.79739537 0.32713282 0.14890839 ... 0.79997654 1.3498841  0.70940842]
40/40 [==============================] - 0s 653us/step
 weights_push at the beginning
[0.77611568 0.33341809 0.14453416 ... 0.75234982 1.35436311 0.72220965]
40/40 [==============================] - 0s 630us/step
 weights_push at the beginning
[0.75004617 0.32174471 0.13885741 ... 0.72671905 1.38817082 0.70136515]
40/40 [==============================] - 0s 557us/step
 weights_push at the beginning
[0.72495533 0.31211955 0.13415253 ... 0.65568273 1.38157128 0.69290645]
40/40 [==============================] - 0s 623us/step
 weights_push at the beginning
[0.73497814 0.31486696 0.1373702  ... 0.61712031 1.42188939 0.70770679]
40/40 [==============================] - 0s 642us/step
 weights_push at the beginning
[0.73076499 0.30577073 0.13593927 ... 0.57055299 1.42079135 0.69396808]
40/40 [==============================] - 0s 619us/st


 Creating bootstrap sample 403
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]
40/40 [==============================] - 0s 639us/step
 weights_push at the beginning
[0.94681138 0.5226382  0.34052721 ... 1.01804948 1.22872889 0.75465351]
40/40 [==============================] - 0s 600us/step
 weights_push at the beginning
[0.92081873 0.44690894 0.26876559 ... 0.94743809 1.24175309 0.6858024 ]
40/40 [==============================] - 0s 613us/step
 weights_push at the beginning
[0.93102538 0.41389796 0.23096846 ... 0.92996038 1.29966213 0.66945679]
40/40 [==============================] - 0s 610us/step
 weights_push at the beginning
[0.93766495 0.42003641 0.24285047 ... 0.87060942 1.31471298 0.64778577]
40/40 [==============================] - 0s 623us/step
 weights_push at the beginning
[0.94600048 0.39157422 0.22084773 ... 0.82521087 1.31980235 0.62420605]
40/40 [==============================] - 0s 621us/step
 weights_push at the beginning
[0.98214979 0.41556845 0.23793234 ...

40/40 [==============================] - 0s 593us/step
 weights_push at the beginning
[0.97826    0.35164746 0.24291599 ... 0.62500908 1.76948703 0.76518026]
40/40 [==============================] - 0s 639us/step
 weights_push at the beginning
[0.9814285  0.33978816 0.24607179 ... 0.58386172 1.82753563 0.77165217]
40/40 [==============================] - 0s 629us/step


 bootstrap 406 final push weights scaled:
[0.09906414 0.03246262 0.02442845 ... 0.05446328 0.19411185 0.07698542]

 Creating bootstrap sample 407
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]
40/40 [==============================] - 0s 643us/step
 weights_push at the beginning
[0.96593094 0.51551759 0.34939033 ... 0.99774384 1.29419148 0.80461723]
40/40 [==============================] - 0s 623us/step
 weights_push at the beginning
[0.95619593 0.40747677 0.25181087 ... 0.93087868 1.35650688 0.74330189]
40/40 [==============================] - 0s 661us/step
 weights_push at the beginning
[0.99120865 0.37810744 0

40/40 [==============================] - 0s 649us/step
 weights_push at the beginning
[1.13352271 0.33227129 0.19672449 ... 0.7368993  1.28542272 0.69865547]
40/40 [==============================] - 0s 630us/step
 weights_push at the beginning
[1.2073808  0.33609491 0.20560307 ... 0.73375901 1.26159907 0.72497908]
40/40 [==============================] - 0s 658us/step
 weights_push at the beginning
[1.23526297 0.33048293 0.21331108 ... 0.68338378 1.21195526 0.71720358]
40/40 [==============================] - 0s 637us/step
 weights_push at the beginning
[1.32866567 0.32689455 0.22147152 ... 0.68033175 1.19634235 0.73552959]
40/40 [==============================] - 0s 672us/step
 weights_push at the beginning
[1.36191665 0.31842539 0.23147155 ... 0.60189623 1.16206089 0.72782984]
40/40 [==============================] - 0s 627us/step


 bootstrap 410 final push weights scaled:
[0.14484674 0.03010617 0.02302463 ... 0.05738111 0.11638836 0.07229652]

 Creating bootstrap sample 411
 weight

40/40 [==============================] - 0s 654us/step
 weights_push at the beginning
[0.96433611 0.38879957 0.24510085 ... 0.8444953  1.1501839  0.69929661]
40/40 [==============================] - 0s 598us/step
 weights_push at the beginning
[0.99233466 0.36513589 0.22839164 ... 0.77413551 1.0925168  0.69474555]
40/40 [==============================] - 0s 612us/step
 weights_push at the beginning
[1.03053098 0.35952536 0.23978981 ... 0.67122397 1.03201213 0.72224225]
40/40 [==============================] - 0s 553us/step
 weights_push at the beginning
[1.07115047 0.35427878 0.2442938  ... 0.57716549 0.99031205 0.73985781]
40/40 [==============================] - 0s 627us/step
 weights_push at the beginning
[1.10617511 0.35493927 0.25820269 ... 0.52395029 0.93978707 0.76479983]
40/40 [==============================] - 0s 668us/step
 weights_push at the beginning
[1.12042485 0.34519254 0.26428039 ... 0.43229068 0.86828793 0.77249377]
40/40 [==============================] - 0s 607us/st

40/40 [==============================] - 0s 654us/step
 weights_push at the beginning
[1.10259917 0.34085713 0.20624993 ... 1.00890751 1.55128937 0.65428404]
40/40 [==============================] - 0s 646us/step


 bootstrap 417 final push weights scaled:
[0.11314925 0.03306442 0.01766843 ... 0.09989794 0.15524957 0.0644021 ]

 Creating bootstrap sample 418
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]
40/40 [==============================] - 0s 646us/step
 weights_push at the beginning
[0.91141808 0.5374943  0.35659739 ... 1.04304504 1.30941117 0.78083044]
40/40 [==============================] - 0s 605us/step
 weights_push at the beginning
[0.93070913 0.44013505 0.23874533 ... 1.06180743 1.4366646  0.73953213]
40/40 [==============================] - 0s 567us/step
 weights_push at the beginning
[0.97670033 0.44523538 0.2337727  ... 1.03350632 1.50271486 0.7670182 ]
40/40 [==============================] - 0s 648us/step
 weights_push at the beginning
[0.97083863 0.41990192 0

40/40 [==============================] - 0s 681us/step
 weights_push at the beginning
[0.95543754 0.40125935 0.27222304 ... 0.607483   1.70559965 0.76840098]
40/40 [==============================] - 0s 650us/step
 weights_push at the beginning
[0.96142214 0.3974746  0.2741285  ... 0.49845093 1.74777704 0.76818998]
40/40 [==============================] - 0s 589us/step
 weights_push at the beginning
[0.9743078  0.39320592 0.27817094 ... 0.45474875 1.76968955 0.77349118]
40/40 [==============================] - 0s 576us/step
 weights_push at the beginning
[0.99852354 0.39230875 0.26659791 ... 0.42040147 1.85130181 0.77924723]
40/40 [==============================] - 0s 608us/step


 bootstrap 421 final push weights scaled:
[0.09643816 0.03757688 0.02694805 ... 0.03641055 0.1871696  0.07450746]

 Creating bootstrap sample 422
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]
40/40 [==============================] - 0s 670us/step
 weights_push at the beginning
[0.90234125 0.52001023 0

40/40 [==============================] - 0s 620us/step
 weights_push at the beginning
[0.88379623 0.37910112 0.23370609 ... 0.97278823 1.33341028 0.69116812]
40/40 [==============================] - 0s 561us/step
 weights_push at the beginning
[0.87882413 0.37667223 0.23313201 ... 0.95592541 1.36611509 0.68582596]
40/40 [==============================] - 0s 566us/step
 weights_push at the beginning
[0.8332608  0.38163166 0.24217731 ... 0.91294806 1.36707137 0.68603117]
40/40 [==============================] - 0s 601us/step
 weights_push at the beginning
[0.84822185 0.37416597 0.23894545 ... 0.91959835 1.39951007 0.68833405]
40/40 [==============================] - 0s 638us/step
 weights_push at the beginning
[0.85416453 0.38647206 0.25625974 ... 0.96207494 1.4382539  0.70488922]
40/40 [==============================] - 0s 626us/step
 weights_push at the beginning
[0.83766135 0.39559956 0.27430858 ... 0.94260667 1.4314449  0.69852896]
40/40 [==============================] - 0s 642us/st

40/40 [==============================] - 0s 638us/step


 bootstrap 428 final push weights scaled:
[0.09014884 0.03382517 0.01887626 ... 0.07361777 0.14211943 0.08212805]

 Creating bootstrap sample 429
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]
40/40 [==============================] - 0s 610us/step
 weights_push at the beginning
[0.97392827 0.51685268 0.36774978 ... 1.01139998 1.24734843 0.77426571]
40/40 [==============================] - 0s 649us/step
 weights_push at the beginning
[0.95609616 0.43426067 0.27688054 ... 0.95425707 1.3195059  0.70449994]
40/40 [==============================] - 0s 628us/step
 weights_push at the beginning
[1.00284323 0.41131946 0.24932558 ... 0.90705668 1.30839552 0.68786124]
40/40 [==============================] - 0s 636us/step
 weights_push at the beginning
[1.03437503 0.38912485 0.22719739 ... 0.84481443 1.3034107  0.65741358]
40/40 [==============================] - 0s 579us/step
 weights_push at the beginning
[1.09340153 0.40178135 0

40/40 [==============================] - 0s 613us/step
 weights_push at the beginning
[0.93468959 0.33972522 0.15018572 ... 0.60178796 1.41301664 0.72215324]
40/40 [==============================] - 0s 640us/step
 weights_push at the beginning
[0.92963881 0.34208538 0.14944021 ... 0.52470105 1.4301446  0.72553389]
40/40 [==============================] - 0s 623us/step
 weights_push at the beginning
[0.94208485 0.34370532 0.14840277 ... 0.47400295 1.45665628 0.72671509]
40/40 [==============================] - 0s 624us/step


 bootstrap 432 final push weights scaled:
[0.09528101 0.03435759 0.01455009 ... 0.04374704 0.15029872 0.07394212]

 Creating bootstrap sample 433
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]
40/40 [==============================] - 0s 647us/step
 weights_push at the beginning
[0.97550344 0.56757182 0.41223589 ... 1.04209685 1.29331183 0.81161362]
40/40 [==============================] - 0s 634us/step
 weights_push at the beginning
[0.95617928 0.42746911 0

40/40 [==============================] - 0s 575us/step
 weights_push at the beginning
[1.02267706 0.38484156 0.21812886 ... 0.8891921  1.39264543 0.72512908]
40/40 [==============================] - 0s 623us/step
 weights_push at the beginning
[1.05612122 0.40001881 0.2294529  ... 0.85358433 1.41651044 0.73709604]
40/40 [==============================] - 0s 635us/step
 weights_push at the beginning
[1.07635125 0.40198475 0.23055639 ... 0.8371642  1.41984663 0.7337728 ]
40/40 [==============================] - 0s 641us/step
 weights_push at the beginning
[1.11873522 0.41697749 0.24265074 ... 0.79052691 1.4343291  0.74933242]
40/40 [==============================] - 0s 664us/step
 weights_push at the beginning
[1.12306407 0.40902127 0.23737223 ... 0.7388036  1.47961953 0.74701848]
40/40 [==============================] - 0s 650us/step
 weights_push at the beginning
[1.13270929 0.41417004 0.24518508 ... 0.69975703 1.45196378 0.73357446]
40/40 [==============================] - 0s 603us/st


 Creating bootstrap sample 440
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]
40/40 [==============================] - 0s 648us/step
 weights_push at the beginning
[0.86246157 0.5156076  0.33953026 ... 1.03582335 1.29229319 0.81991678]
40/40 [==============================] - 0s 640us/step
 weights_push at the beginning
[0.78581971 0.44191351 0.25793031 ... 0.99349047 1.42652604 0.75559102]
40/40 [==============================] - 0s 636us/step
 weights_push at the beginning
[0.77930775 0.44579061 0.25692034 ... 0.97470476 1.50433325 0.77412237]
40/40 [==============================] - 0s 590us/step
 weights_push at the beginning
[0.77512215 0.43648384 0.2454141  ... 0.98396692 1.61012658 0.79245662]
40/40 [==============================] - 0s 623us/step
 weights_push at the beginning
[0.75354094 0.42334503 0.23367545 ... 0.94429245 1.67825795 0.78414497]
40/40 [==============================] - 0s 599us/step
 weights_push at the beginning
[0.75982798 0.44967182 0.24692309 ...

40/40 [==============================] - 0s 634us/step
 weights_push at the beginning
[1.30958603 0.33598391 0.21162941 ... 0.45268735 2.1466797  0.83656148]
40/40 [==============================] - 0s 625us/step
 weights_push at the beginning
[1.40120357 0.33359202 0.21200539 ... 0.40180627 2.27705161 0.86179054]
40/40 [==============================] - 0s 648us/step


 bootstrap 443 final push weights scaled:
[0.14597803 0.03239109 0.02113524 ... 0.03760499 0.23633909 0.08695774]

 Creating bootstrap sample 444
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]
40/40 [==============================] - 0s 653us/step
 weights_push at the beginning
[0.94537717 0.46159738 0.27415258 ... 0.96307087 1.25318325 0.76649278]
40/40 [==============================] - 0s 554us/step
 weights_push at the beginning
[0.94474651 0.38772217 0.18673449 ... 0.85679007 1.30603423 0.73784185]
40/40 [==============================] - 0s 587us/step
 weights_push at the beginning
[0.973313   0.37990243 0

40/40 [==============================] - 0s 631us/step
 weights_push at the beginning
[1.09331238 0.36551988 0.18877054 ... 0.62703091 1.5409917  0.72893428]
40/40 [==============================] - 0s 637us/step
 weights_push at the beginning
[1.14861436 0.35848629 0.18213069 ... 0.59687947 1.60515481 0.73010764]
40/40 [==============================] - 0s 652us/step
 weights_push at the beginning
[1.20470986 0.34765949 0.17406859 ... 0.55748263 1.61891225 0.72240907]
40/40 [==============================] - 0s 649us/step
 weights_push at the beginning
[1.28121833 0.36025642 0.18686042 ... 0.52736343 1.71490806 0.74537559]
40/40 [==============================] - 0s 589us/step
 weights_push at the beginning
[1.31929638 0.34547616 0.17497991 ... 0.49101373 1.71704316 0.72322906]
40/40 [==============================] - 0s 611us/step


 bootstrap 447 final push weights scaled:
[0.14033509 0.03636029 0.01881524 ... 0.04334007 0.17597246 0.07439296]

 Creating bootstrap sample 448
 weight

40/40 [==============================] - 0s 631us/step
 weights_push at the beginning
[0.93201757 0.41297017 0.18836111 ... 0.97757377 1.30763673 0.74052278]
40/40 [==============================] - 0s 633us/step
 weights_push at the beginning
[0.93449022 0.42833851 0.18183861 ... 0.99400836 1.36400788 0.74665504]
40/40 [==============================] - 0s 599us/step
 weights_push at the beginning
[0.92294434 0.41718242 0.16418062 ... 0.9185371  1.35720541 0.74513389]
40/40 [==============================] - 0s 617us/step
 weights_push at the beginning
[0.9234477  0.41926589 0.15723378 ... 0.88779297 1.37848568 0.75391487]
40/40 [==============================] - 0s 628us/step
 weights_push at the beginning
[0.93874348 0.4280376  0.15467459 ... 0.80249408 1.38083689 0.75730167]
40/40 [==============================] - 0s 602us/step
 weights_push at the beginning
[0.94659352 0.43039031 0.14654198 ... 0.79304891 1.36004576 0.74459856]
40/40 [==============================] - 0s 637us/st

40/40 [==============================] - 0s 627us/step
 weights_push at the beginning
[0.86952982 0.39418008 0.16411744 ... 0.40152817 1.70057642 0.69471296]
40/40 [==============================] - 0s 648us/step


 bootstrap 454 final push weights scaled:
[0.08529644 0.03972108 0.01611272 ... 0.03502029 0.17049914 0.06946775]

 Creating bootstrap sample 455
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]
40/40 [==============================] - 0s 562us/step
 weights_push at the beginning
[0.9697538  0.47209182 0.32402238 ... 0.93744683 1.24795222 0.73441494]
40/40 [==============================] - 0s 656us/step
 weights_push at the beginning
[1.01349175 0.4057027  0.2452736  ... 0.83447697 1.38041406 0.69196913]
40/40 [==============================] - 0s 632us/step
 weights_push at the beginning
[1.03981091 0.3884295  0.24050489 ... 0.78155335 1.45805935 0.67621943]
40/40 [==============================] - 0s 567us/step
 weights_push at the beginning
[1.05933223 0.38868121 0

40/40 [==============================] - 0s 578us/step
 weights_push at the beginning
[1.10858087 0.38298239 0.19672506 ... 0.88394733 1.13282827 0.76740145]
40/40 [==============================] - 0s 641us/step
 weights_push at the beginning
[1.16543474 0.39292826 0.20316969 ... 0.81723728 1.08577811 0.78932295]
40/40 [==============================] - 0s 620us/step
 weights_push at the beginning
[1.20993659 0.38394761 0.19865253 ... 0.72316964 1.02273662 0.7836211 ]
40/40 [==============================] - 0s 599us/step
 weights_push at the beginning
[1.28119478 0.39097199 0.20000658 ... 0.66297043 1.00306506 0.79480763]
40/40 [==============================] - 0s 620us/step


 bootstrap 458 final push weights scaled:
[0.12908669 0.03942317 0.02014244 ... 0.06324967 0.09340331 0.07694115]

 Creating bootstrap sample 459
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]
40/40 [==============================] - 0s 640us/step
 weights_push at the beginning
[0.97217751 0.45336679 0

40/40 [==============================] - 0s 587us/step
 weights_push at the beginning
[1.00720321 0.41988043 0.25176519 ... 0.60946547 1.2963379  0.67423628]
40/40 [==============================] - 0s 622us/step
 weights_push at the beginning
[1.0193015  0.41783524 0.2391044  ... 0.50495139 1.30738735 0.66250243]
40/40 [==============================] - 0s 656us/step
 weights_push at the beginning
[1.00355724 0.40853868 0.2240416  ... 0.41601075 1.27227591 0.63679516]
40/40 [==============================] - 0s 627us/step
 weights_push at the beginning
[1.03098761 0.43053042 0.23369333 ... 0.34015799 1.24146762 0.64470222]
40/40 [==============================] - 0s 627us/step
 weights_push at the beginning
[1.01931573 0.41956689 0.21482115 ... 0.26932946 1.18904339 0.61465503]
40/40 [==============================] - 0s 602us/step
 weights_push at the beginning
[1.01329536 0.42792806 0.21111736 ... 0.22280795 1.13310592 0.600081  ]
40/40 [==============================] - 0s 650us/st

40/40 [==============================] - 0s 628us/step


 bootstrap 465 final push weights scaled:
[0.08737114 0.03855111 0.01774122 ... 0.01824669 0.13159894 0.06253646]

 Creating bootstrap sample 466
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]
40/40 [==============================] - 0s 613us/step
 weights_push at the beginning
[0.95192403 0.50106567 0.34690848 ... 0.94447291 1.16602421 0.75032324]
40/40 [==============================] - 0s 610us/step
 weights_push at the beginning
[0.99513005 0.41254212 0.24601485 ... 0.81840989 1.22966064 0.69616224]
40/40 [==============================] - 0s 640us/step
 weights_push at the beginning
[1.05938685 0.38934974 0.22280008 ... 0.71885283 1.23066695 0.67496946]
40/40 [==============================] - 0s 569us/step
 weights_push at the beginning
[1.13360865 0.37552324 0.20963548 ... 0.62716795 1.17714731 0.66143344]
40/40 [==============================] - 0s 659us/step
 weights_push at the beginning
[1.13409987 0.37544606 0

40/40 [==============================] - 0s 624us/step
 weights_push at the beginning
[0.80970698 0.32453324 0.14126044 ... 0.16863447 1.07736836 0.70301626]
40/40 [==============================] - 0s 572us/step
 weights_push at the beginning
[0.79181373 0.32266662 0.13802251 ... 0.12152346 1.03100314 0.70922118]
40/40 [==============================] - 0s 645us/step
 weights_push at the beginning
[0.77378301 0.32731017 0.1402744  ... 0.08451314 1.03270304 0.71555611]
40/40 [==============================] - 0s 646us/step


 bootstrap 469 final push weights scaled:
[0.07587558 0.03195333 0.01356648 ... 0.00589966 0.10328018 0.06987236]

 Creating bootstrap sample 470
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]
40/40 [==============================] - 0s 649us/step
 weights_push at the beginning
[0.94015962 0.49709272 0.35340038 ... 0.81418622 1.27377391 0.77191705]
40/40 [==============================] - 0s 616us/step
 weights_push at the beginning
[0.88150174 0.3932546  0

40/40 [==============================] - 0s 656us/step
 weights_push at the beginning
[0.96424123 0.33989989 0.21771554 ... 0.46818126 1.24377914 0.77677362]
40/40 [==============================] - 0s 620us/step
 weights_push at the beginning
[0.98958556 0.33291286 0.21785419 ... 0.36212005 1.22980535 0.80143634]
40/40 [==============================] - 0s 625us/step
 weights_push at the beginning
[0.98332861 0.32520076 0.22325607 ... 0.21636922 1.19906648 0.80881631]
40/40 [==============================] - 0s 640us/step
 weights_push at the beginning
[1.00879518 0.31756597 0.22233606 ... 0.16800767 1.17276869 0.83214591]
40/40 [==============================] - 0s 633us/step
 weights_push at the beginning
[0.99933529 0.31546886 0.22910542 ... 0.11550792 1.13957292 0.84104619]
40/40 [==============================] - 0s 595us/step
 weights_push at the beginning
[0.99099589 0.30897963 0.23371937 ... 0.07716015 1.09045896 0.84241384]
40/40 [==============================] - 0s 639us/st


 Creating bootstrap sample 477
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]
40/40 [==============================] - 0s 625us/step
 weights_push at the beginning
[0.93802041 0.48910698 0.32746449 ... 0.78649443 1.17997921 0.76670045]
40/40 [==============================] - 0s 636us/step
 weights_push at the beginning
[1.01585536 0.4078354  0.25106791 ... 0.60673821 1.22272109 0.7387733 ]
40/40 [==============================] - 0s 577us/step
 weights_push at the beginning
[1.01276533 0.39101747 0.24006981 ... 0.51154381 1.28992652 0.74311261]
40/40 [==============================] - 0s 624us/step
 weights_push at the beginning
[0.97962261 0.38002141 0.23686178 ... 0.35690752 1.30792591 0.74335286]
40/40 [==============================] - 0s 646us/step
 weights_push at the beginning
[0.95841657 0.38763877 0.24894907 ... 0.27847135 1.31598666 0.76301758]
40/40 [==============================] - 0s 638us/step
 weights_push at the beginning
[0.93247698 0.39951048 0.26887875 ...

40/40 [==============================] - 0s 617us/step
 weights_push at the beginning
[1.01591067 0.31256468 0.15975613 ... 0.56590182 1.31480518 0.75004737]
40/40 [==============================] - 0s 634us/step
 weights_push at the beginning
[1.01162873 0.30943274 0.16151537 ... 0.55115858 1.28437916 0.74344304]
40/40 [==============================] - 0s 640us/step


 bootstrap 480 final push weights scaled:
[0.09978556 0.03056341 0.01655726 ... 0.05136548 0.12273129 0.07272931]

 Creating bootstrap sample 481
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]
40/40 [==============================] - 0s 632us/step
 weights_push at the beginning
[0.93708313 0.47659546 0.31278443 ... 0.96118414 1.23639822 0.76088005]
40/40 [==============================] - 0s 623us/step
 weights_push at the beginning
[0.95529862 0.39587102 0.23244012 ... 0.91039461 1.33928863 0.71035218]
40/40 [==============================] - 0s 622us/step
 weights_push at the beginning
[0.95117683 0.38287998 0

40/40 [==============================] - 0s 684us/step
 weights_push at the beginning
[0.96978592 0.39100058 0.20902508 ... 0.82165456 1.27116907 0.80471174]
40/40 [==============================] - 0s 612us/step
 weights_push at the beginning
[0.94953923 0.40463147 0.22447046 ... 0.79784158 1.24118769 0.80710987]
40/40 [==============================] - 0s 598us/step
 weights_push at the beginning
[0.98902285 0.42627662 0.23056763 ... 0.79039246 1.23591761 0.8363752 ]
40/40 [==============================] - 0s 643us/step
 weights_push at the beginning
[1.01454093 0.42856553 0.22688611 ... 0.7787263  1.23753606 0.85847662]
40/40 [==============================] - 0s 617us/step
 weights_push at the beginning
[1.00098827 0.42234777 0.2145911  ... 0.7772163  1.22887784 0.87166517]
40/40 [==============================] - 0s 641us/step


 bootstrap 484 final push weights scaled:
[0.10207457 0.04113112 0.01968852 ... 0.07521194 0.11901957 0.08829956]

 Creating bootstrap sample 485
 weight

40/40 [==============================] - 0s 641us/step
 weights_push at the beginning
[1.00994523 0.36274784 0.22870525 ... 0.99185293 1.25207018 0.74631741]
40/40 [==============================] - 0s 648us/step
 weights_push at the beginning
[1.01739635 0.32020464 0.22450714 ... 0.92487224 1.25223496 0.74004672]
40/40 [==============================] - 0s 611us/step
 weights_push at the beginning
[1.10996058 0.31366407 0.22723593 ... 0.92324109 1.23153241 0.77731748]
40/40 [==============================] - 0s 630us/step
 weights_push at the beginning
[1.13127179 0.29005157 0.22820609 ... 0.93982873 1.24319809 0.78350545]
40/40 [==============================] - 0s 633us/step
 weights_push at the beginning
[1.15235051 0.28334236 0.25299618 ... 0.94909324 1.24381712 0.80568121]
40/40 [==============================] - 0s 597us/step
 weights_push at the beginning
[1.20957057 0.27800605 0.27677544 ... 0.96267567 1.2465519  0.81610783]
40/40 [==============================] - 0s 635us/st

40/40 [==============================] - 0s 655us/step
 weights_push at the beginning
[0.9970563  0.30942646 0.13809877 ... 0.77394935 1.31474947 0.72730433]
40/40 [==============================] - 0s 637us/step


 bootstrap 491 final push weights scaled:
[0.10310406 0.0309227  0.01358055 ... 0.07796618 0.13396591 0.07399362]

 Creating bootstrap sample 492
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]
40/40 [==============================] - 0s 661us/step
 weights_push at the beginning
[0.91114527 0.52840215 0.36997867 ... 0.9771753  1.21990228 0.77204454]
40/40 [==============================] - 0s 603us/step
 weights_push at the beginning
[0.86328173 0.4220968  0.29231334 ... 0.92457969 1.27613005 0.72132407]
40/40 [==============================] - 0s 598us/step
 weights_push at the beginning
[0.82973093 0.39743103 0.29825306 ... 0.87258891 1.29367314 0.7070949 ]
40/40 [==============================] - 0s 632us/step
 weights_push at the beginning
[0.84288835 0.38438472 0

40/40 [==============================] - 0s 615us/step
 weights_push at the beginning
[0.75818599 0.36428696 0.22959029 ... 0.90991021 1.44199984 0.70448239]
40/40 [==============================] - 0s 609us/step
 weights_push at the beginning
[0.75127555 0.37065761 0.23318336 ... 0.878209   1.46500673 0.72242666]
40/40 [==============================] - 0s 625us/step
 weights_push at the beginning
[0.74952373 0.37262229 0.23017451 ... 0.86276053 1.48655918 0.74555177]
40/40 [==============================] - 0s 613us/step
 weights_push at the beginning
[0.73977857 0.37414412 0.22872483 ... 0.85145187 1.48051617 0.76148318]
40/40 [==============================] - 0s 604us/step


 bootstrap 495 final push weights scaled:
[0.07279532 0.03672534 0.02215682 ... 0.08410797 0.14643081 0.07594316]

 Creating bootstrap sample 496
 weights_push at the beginning
[1. 1. 1. ... 1. 1. 1.]
40/40 [==============================] - 0s 661us/step
 weights_push at the beginning
[0.96862561 0.52800727 0

40/40 [==============================] - 0s 643us/step
 weights_push at the beginning
[1.07401919 0.39079119 0.18595613 ... 0.90429973 1.38737517 0.70395042]
40/40 [==============================] - 0s 634us/step
 weights_push at the beginning
[1.11085149 0.3810971  0.17218461 ... 0.89103046 1.4077389  0.69811459]
40/40 [==============================] - 0s 654us/step
 weights_push at the beginning
[1.16587067 0.39589585 0.16765444 ... 0.86841397 1.4624956  0.71026072]
40/40 [==============================] - 0s 610us/step
 weights_push at the beginning
[1.18291967 0.42752321 0.18012788 ... 0.82796804 1.47923323 0.69933702]
40/40 [==============================] - 0s 672us/step
 weights_push at the beginning
[1.22284765 0.44014667 0.17880278 ... 0.79480351 1.53399281 0.69658902]
40/40 [==============================] - 0s 635us/step
 weights_push at the beginning
[1.24646696 0.41562851 0.16973823 ... 0.75188467 1.5605331  0.66983922]
40/40 [==============================] - 0s 646us/st